### ISSUE TITLE
关于头寸权限管理方案的讨论

### ISSUE THREAD

**Issue by yutingzhao1991** [WTFAcademy/WTF-Dapp#103]
要添加流动性和提取流动性，按照当前的设计应该是 DApp 前端调用 PositionManager，然后 PositionManager 调用 Pool，需要确认的点是：

- 每个 LP 拥有的头寸信息是存放在 PositionManger 里面还是存放在 Pool？
- Pool 在做 burn 操作提取头寸的时候如何判断权限？

**Comment by yutingzhao1991** [comment]
> 我目前的想法是 Pool 里面应该有完整的信息，它通过 msg.sender 来做权限管理。burn 操作应该是直接调用 Pool 合约，而不是调用 PositionManager 合约。
> 
> mint 方法理论上 LP 也可以直接调用 Pool 的 Mint 合约，但是我们 DApp 是通过 PositionManager 来调用，这样 PositionManager 合约可以记录每个用户有哪些头寸。PositionManager 调用 mint 的时候指定头寸在 Pool 合约中的 owner，这样 LP 就可以直接通过调用 Pool 的 burn 来提取头寸了。
> 
> 所以 PositionManager 中的 burn 方法应该删掉，LP 直接调用 Pool 合约的 burn 方法，Pool 合约中通过 `msg.sender` 来判断权限。

不过这样有一个问题，如果 burn 直接通过嗲用 Pool 的方法来处理的话，PositionManager 就不知道某个头寸已经被提取了。UI 中就没法响应，这个得想想怎么解决。

**Comment by AmazingAng** [comment]
真的考虑下用uni v3合约源码吧。

**Comment by yutingzhao1991** [comment]
> 真的考虑下用uni v3合约源码吧。

直接用 uni v3 也不是不可以，只不过就是另外一种形式的课程了。直接用 v3 其实课程就偏向合约部署、前端调用、整体结构理解这样了。但是对于合约代码编写、常见问题处理、Solidity 语法等合约开发上的内容就会弱很多。

其实本质上还是要看课程面向的人群，课程的定位来看。

直接用 V3 的合约的话那涉及到 Uniswap V3 这部分的课程其实就更像是一个小的章节，课程可能更多内容就和 Uniswap 不要直接关联，而是展开丰富现有的课程。

如果是按照现在思路去重写一个 Wtfswap 的话，就更像是以  Wtfswap 为主体，以一个实战任务的形式来教学。

其实都可以，是两种不同的教学思路。这两种选择对于的课程章节的设计也会有所不同了。可以继续讨论。

**Comment by yutingzhao1991** [comment]
## 用 uni 源码的课程大纲

基础课程：
- 快速开始
- 节点服务
- 合约调用
- 合约部署
- ....
- 
进阶课程：
- 合约权限管控
- Gas 优化
- ....

扩展实战：
- 部署一个 Uniswap V3
- 部署一个 NFT 项目

## 自研合约的课程大纲

基础课程：
- 快速开始
- 节点服务
- 合约调用
- 合约部署
- ......

DEX 开发实战：
- Wtfswap 整体设计
- Pool 合约 LP 相关接口开发
- ...


@AmazingAng 其实也不冲突，也可以都要，或者分开为不同的课程。只是课程设计的逻辑不同，适用的场景和人群也不同。前者其实简单多了。搞 Wtfswap 这个也是想要虐一虐自己，从头搞一个新的合约实战看看。

**Comment by Web3Pignard** [comment]
> 我目前的想法是 Pool 里面应该有完整的信息，它通过 msg.sender 来做权限管理。burn 操作应该是直接调用 Pool 合约，而不是调用 PositionManager 合约。
> 
> mint 方法理论上 LP 也可以直接调用 Pool 的 Mint 合约，但是我们 DApp 是通过 PositionManager 来调用，这样 PositionManager 合约可以记录每个用户有哪些头寸。PositionManager 调用 mint 的时候指定头寸在 Pool 合约中的 owner，这样 LP 就可以直接通过调用 Pool 的 burn 来提取头寸了。
> 
> 所以 PositionManager 中的 burn 方法应该删掉，LP 直接调用 Pool 合约的 burn 方法，Pool 合约中通过 `msg.sender` 来判断权限。

我觉得面向用户直接操作还是 PositionManager 比较好，Pool 合约逻辑里所有涉及权限控制的地方都回调 PositionManager，PositionManager 再去判断（前提是缓存了 msg.sender）

**Comment by yutingzhao1991** [comment]
> > 我目前的想法是 Pool 里面应该有完整的信息，它通过 msg.sender 来做权限管理。burn 操作应该是直接调用 Pool 合约，而不是调用 PositionManager 合约。
> > mint 方法理论上 LP 也可以直接调用 Pool 的 Mint 合约，但是我们 DApp 是通过 PositionManager 来调用，这样 PositionManager 合约可以记录每个用户有哪些头寸。PositionManager 调用 mint 的时候指定头寸在 Pool 合约中的 owner，这样 LP 就可以直接通过调用 Pool 的 burn 来提取头寸了。
> > 所以 PositionManager 中的 burn 方法应该删掉，LP 直接调用 Pool 合约的 burn 方法，Pool 合约中通过 `msg.sender` 来判断权限。
> 
> 我觉得面向用户直接操作还是 PositionManager 比较好，Pool 合约逻辑里所有涉及权限控制的地方都回调 PositionManager，PositionManager 再去判断（前提是缓存了 msg.sender）

这样感觉合约 PositionManager 和 Pool 有点过渡耦合了，我感觉 PositionManager 这个更多应该是一个辅助 dapp 的合约，不是必须的。核心的逻辑 Pool 自己可以独立完成，和 PositionManager 解耦。这样 DApp 也可以不直接用 PositionManager，理论上也可以类似 Uniswap 一样，通过服务端来提供 PositionManager 现在提供的接口。

**Comment by yutingzhao1991** [comment]
最后确认的方案，PositionManager 作为一个代理，课程的前端都走 PositionManager，但是理论上 LP 也可以直接走 Pool 注入或者提取流动性。具体见 https://github.com/WTFAcademy/WTF-Dapp/pull/107 的说明。
