### ISSUE TITLE
课程进度问询

### ISSUE THREAD

**Issue by weixin3046** [WTFAcademy/WTF-Dapp#108]
你好，我是一名web3开发，专注于defi产品，关注课程很久了，但是课程好像很久都没有更新了，其他课程有在开发吗，课程需要帮忙吗

**Comment by yutingzhao1991** [comment]
在更新，只是之前进度比较慢，最近正准备加快进度，很欢迎来贡献，可以参考 https://github.com/WTFAcademy/WTF-Dapp/issues/59 这里的说明：

## 如何参与贡献

下面的课程列表都已经有社区的同学认领了，但是因为大家时间问题，进度比较慢。为了加快进度，欢迎更多的同学直接参与贡献。如果对课程感兴趣，**你可以直接提 PR 补充课程内容，可以是一个还未实现的合约的方法，也可以是一个错别字，任何贡献都可以。**

如果担心你正在处理的内容已经有其他社区同学已经再做，你可以先提个对应的 ISSUE 指给自己，如果其他同学有异议可以直接在 ISSUE 下面讨论。或者你也可以到其他同学创建的对应的 ISSUE 下面确认是否可以“抢”过某一部分开发任务。当然，即便有冲突也没关系，大家也可以一起帮忙 review 就行，谁先提交了合适的 PR 就优先合并谁的，保持开放的态度。
