### ISSUE TITLE
关于合约本地开发的问题

### ISSUE THREAD

**Issue by charles-chenzz** [WTFAcademy/WTF-Dapp#126]
我是web2 go后端的开发 nodejs ts这套不熟 想问下本地开发的话能不能用go+solidity 如果可以的话怎么操作 包括dapp的开发 我看是用的js去调用web3.js然后顺便连带css一起写了，在想有没有办法隔离开 比如react写纯页面 然后通过go去和solidity contract交互这样

@yutingzhao1991

**Comment by yutingzhao1991** [comment]
- 合约本地开发建议还是用 Node 这一套，JS 的生态更完善一些，hardhat 也比较成熟了，其实都是工具，没有太多语言特性需要注意的，上手应该还是比较快。go 的生态了解得不多，不知道有没有类似的。
- 调用合约肯定得用 JS 的，因为要在浏览器端唤起钱包做交易。所以肯定会用到类似 web3.js 或者 ethers、viem、wagmi、Ant Design Web3 这样的库。不过理论上也可以让前端来签名，由服务端来调用合约，也有这样的情况的。具体还是要看场景吧，不要从技术上做限制。

**Comment by charles-chenzz** [comment]
> 调用合约肯定得用 JS 的，因为要在浏览器端唤起钱包做交易。所以肯定会用到类似 web3.js 或者 ethers、viem、wagmi、Ant Design Web3 这样的库。不过理论上也可以让前端来签名，由服务端来调用合约，也有这样的情况的。具体还是要看场景吧，不要从技术上做限制。

如果做的是那种纯后端的也需要js吗 就是比如我想swap sign全部在后端处理 用go-eth那个库 还是说浏览器端+contract那套是web2里的前后端分离

**Comment by yutingzhao1991** [comment]
> > 调用合约肯定得用 JS 的，因为要在浏览器端唤起钱包做交易。所以肯定会用到类似 web3.js 或者 ethers、viem、wagmi、Ant Design Web3 这样的库。不过理论上也可以让前端来签名，由服务端来调用合约，也有这样的情况的。具体还是要看场景吧，不要从技术上做限制。
> 
> 如果做的是那种纯后端的也需要js吗 就是比如我想swap sign全部在后端处理 用go-eth那个库 还是说浏览器端+contract那套是web2里的前后端分离

这个要看你私钥在哪里，私钥如果是在用户钱包那肯定得钱包签名。但是如果你的 dapp 是帮助用户托管私钥的那是可以后端来做的。
