### ISSUE TITLE
error  Ant Design CSS-in-JS

### ISSUE THREAD

**Issue by weixin3046** [WTFAcademy/WTF-Dapp#43]
client.js:2 Warning: [Ant Design CSS-in-JS] Error in ConnectModal: You seem to be using hashed animation 'ripple 3s infinite ease-out', in which case 'animationName' with Keyframe as value is recommended. Selector: :where(.css-dev-only-do-not-override-1okl62o).ant-web3-connect-modal-body | .ant-web3-connect-modal-link-panel | .ant-web3-connect-modal-ripple

**Comment by yutingzhao1991** [comment]
fixed in https://github.com/ant-design/ant-design-web3/pull/859
