### ISSUE TITLE
Swap 页面开发

### ISSUE THREAD

**Issue by Likang0122** [WTFAcademy/WTF-Dapp#60]

**Comment by weixin3046** [comment]
认领swap页面开发

**Comment by yutingzhao1991** [comment]
> 认领swap页面开发

👍，可以先 PR 提起来，写起来。 @Likang0122  可以帮忙一起 review

**Comment by smallfu6** [comment]
@weixin3046 @yutingzhao1991 请确认开发进度，我等待认领

**Comment by yutingzhao1991** [comment]
目前还没有开发到这部分，那 @smallfu6 你这边来吧。
