### ISSUE TITLE
关于Next.js 的问题

### ISSUE THREAD

**Issue by sikamedia** [WTFAcademy/WTF-Dapp#68]
我对next.js 框架刚接触：
我在第一讲里看代码 pages/web3.tsx

`import { Address } from "@ant-design/web3";

export default function Web3() {
  return (
    <Address format address="0xEcd0D12E21805803f70de03B72B1C162dB0898d9" />
  );
}`

我把它写成这样：

`import { Address } from "@ant-design/web3";

export default Web3  = ()  =>  {
  return (
    <Address format address="0xEcd0D12E21805803f70de03B72B1C162dB0898d9" />
  );
}`

报错：

⨯ Error: The default export is not a React Component in page: "/web3" at e6

希望给出解释，是next.js 框架 不认 Web3  = ()  =>  {} , 还是没有 App Router  设置问题  ？ 谢谢

**Comment by yutingzhao1991** [comment]
看上去就是写法不对，`export default Web3 = () => {` 这样改为：

```
const Web3 = () => {
}

export default Web3;
```

试试看
