### ISSUE TITLE
Pool 页面开发，查看所有 Pool

### ISSUE THREAD

**Issue by yutingzhao1991** [WTFAcademy/WTF-Dapp#73]

**Comment by yutingzhao1991** [comment]
@anthhub Pool 页面重新定义了一下，新建了一个 issue，你可以来跟进

**Comment by anthhub** [comment]
ok  有新稿子吗

**Comment by yutingzhao1991** [comment]
> ok 有新稿子吗 @yutingzhao1991

我直接基于之前稿子自己改的，下面是我导出的图：

![Pool](https://github.com/WTFAcademy/WTF-Dapp/assets/1061968/b1250a18-f2e0-4bb5-8213-af6fe4e31be4)

**Comment by anthhub** [comment]
> > ok 有新稿子吗 @yutingzhao1991
> 
> 我直接基于之前稿子自己改的，下面是我导出的图：
> 
> ![Pool](https://private-user-images.githubusercontent.com/1061968/334248386-b1250a18-f2e0-4bb5-8213-af6fe4e31be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjM2MDUsIm5iZiI6MTcxNjg2MzMwNSwicGF0aCI6Ii8xMDYxOTY4LzMzNDI0ODM4Ni1iMTI1MGExOC1mMmUwLTRiYjUtODIxMy1hZjZmZTRlMzFiZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDIyODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc1YjM5Y2Y5MTdjMWI1MzkyZWQ3NGY1Njc4MjhjNzM0NTI0MDcyZWY0MWUxNGFlYTcyZGViZTY3ZTMyNTE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yLT9uBp_u0u9nIpnsNLICSKbBulqTSwrwVw6eJRRIrc)

ok 这个UI 我做完了，等合约的接口

**Comment by yutingzhao1991** [comment]
> > > ok 有新稿子吗 @yutingzhao1991
> > 
> > 
> > 我直接基于之前稿子自己改的，下面是我导出的图：
> > ![Pool](https://private-user-images.githubusercontent.com/1061968/334248386-b1250a18-f2e0-4bb5-8213-af6fe4e31be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjM2MDUsIm5iZiI6MTcxNjg2MzMwNSwicGF0aCI6Ii8xMDYxOTY4LzMzNDI0ODM4Ni1iMTI1MGExOC1mMmUwLTRiYjUtODIxMy1hZjZmZTRlMzFiZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDIyODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc1YjM5Y2Y5MTdjMWI1MzkyZWQ3NGY1Njc4MjhjNzM0NTI0MDcyZWY0MWUxNGFlYTcyZGViZTY3ZTMyNTE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yLT9uBp_u0u9nIpnsNLICSKbBulqTSwrwVw6eJRRIrc)
> 
> ok 这个UI 我做完了，等合约的接口

合约接口定义也快了，PR 在 https://github.com/WTFAcademy/WTF-Dapp/pull/71 这里，你也可以帮忙 review 下

**Comment by smallfu6** [comment]
@yutingzhao1991 认领

**Comment by smallfu6** [comment]
> > > ok 有新稿子吗 @yutingzhao1991
> > 
> > 
> > 我直接基于之前稿子自己改的，下面是我导出的图：
> > ![Pool](https://private-user-images.githubusercontent.com/1061968/334248386-b1250a18-f2e0-4bb5-8213-af6fe4e31be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjM2MDUsIm5iZiI6MTcxNjg2MzMwNSwicGF0aCI6Ii8xMDYxOTY4LzMzNDI0ODM4Ni1iMTI1MGExOC1mMmUwLTRiYjUtODIxMy1hZjZmZTRlMzFiZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDIyODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc1YjM5Y2Y5MTdjMWI1MzkyZWQ3NGY1Njc4MjhjNzM0NTI0MDcyZWY0MWUxNGFlYTcyZGViZTY3ZTMyNTE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yLT9uBp_u0u9nIpnsNLICSKbBulqTSwrwVw6eJRRIrc)
> 
> ok 这个UI 我做完了，等合约的接口

@anthhub 可以提交一下

**Comment by yutingzhao1991** [comment]
UI 部分我做了，大家帮忙 review 一下 https://github.com/WTFAcademy/WTF-Dapp/pull/167
