### ISSUE TITLE
PoolManager.sol 合约开发

### ISSUE THREAD

**Issue by Likang0122** [WTFAcademy/WTF-Dapp#83]

**Comment by yutingzhao1991** [comment]
@0xelilee 认领

**Comment by 0xelilee** [comment]
https://github.com/WTFAcademy/WTF-Dapp/pull/95 
PoolManager.sol 代码我提了一个Pr 需要review一下

**Comment by yutingzhao1991** [comment]
https://github.com/WTFAcademy/WTF-Dapp/pull/114
